apiVersion: v1
kind: Pod
metadata:
 name: node500
spec:
 containers:
   - image: mauriballesagetic/node500
     name: node500
     ports:
       - containerPort: 3000
         protocol: TCP
     livenessProbe:
       httpGet:
         path: /
         port: 3000
       initialDelaySeconds: 5
